# Benchmark config -- All_Beauty (medium, ~693K rows)
dataset:
  source_path: "data/parquet/All_Beauty.parquet"
  fractions: [0.10, 0.25, 0.50, 0.75, 1.0]

embedding:
  model_name: "all-MiniLM-L6-v2"
  dimension: 384
  batch_size: 512
  normalize: true

queries:
  num_queries: 50
  seed: 42

strategies:
  - name: "filter_first"
  - name: "vector_first"
  - name: "hybrid_parallel"
  - name: "adaptive"

output:
  results_dir: "results/raw_metrics/all_beauty"

misc:
  num_repetitions: 3
  warm_up_runs: 2
  log_level: "INFO"
